/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthReturnRouteImport } from './routes/auth.return'
import { Route as ApiSubmissionsRouteImport } from './routes/api/submissions'
import { Route as ApiStatsRouteImport } from './routes/api/stats'
import { Route as ApiClientsRouteImport } from './routes/api/clients'
import { Route as ApiClientsIdRouteImport } from './routes/api/clients/$id'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthReturnRoute = AuthReturnRouteImport.update({
  id: '/auth/return',
  path: '/auth/return',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubmissionsRoute = ApiSubmissionsRouteImport.update({
  id: '/api/submissions',
  path: '/api/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatsRoute = ApiStatsRouteImport.update({
  id: '/api/stats',
  path: '/api/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClientsRoute = ApiClientsRouteImport.update({
  id: '/api/clients',
  path: '/api/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClientsIdRoute = ApiClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiClientsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/clients': typeof ApiClientsRouteWithChildren
  '/api/stats': typeof ApiStatsRoute
  '/api/submissions': typeof ApiSubmissionsRoute
  '/auth/return': typeof AuthReturnRoute
  '/api/clients/$id': typeof ApiClientsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/clients': typeof ApiClientsRouteWithChildren
  '/api/stats': typeof ApiStatsRoute
  '/api/submissions': typeof ApiSubmissionsRoute
  '/auth/return': typeof AuthReturnRoute
  '/api/clients/$id': typeof ApiClientsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/clients': typeof ApiClientsRouteWithChildren
  '/api/stats': typeof ApiStatsRoute
  '/api/submissions': typeof ApiSubmissionsRoute
  '/auth/return': typeof AuthReturnRoute
  '/api/clients/$id': typeof ApiClientsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/api/clients'
    | '/api/stats'
    | '/api/submissions'
    | '/auth/return'
    | '/api/clients/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/api/clients'
    | '/api/stats'
    | '/api/submissions'
    | '/auth/return'
    | '/api/clients/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/api/clients'
    | '/api/stats'
    | '/api/submissions'
    | '/auth/return'
    | '/api/clients/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApiClientsRoute: typeof ApiClientsRouteWithChildren
  ApiStatsRoute: typeof ApiStatsRoute
  ApiSubmissionsRoute: typeof ApiSubmissionsRoute
  AuthReturnRoute: typeof AuthReturnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/return': {
      id: '/auth/return'
      path: '/auth/return'
      fullPath: '/auth/return'
      preLoaderRoute: typeof AuthReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/submissions': {
      id: '/api/submissions'
      path: '/api/submissions'
      fullPath: '/api/submissions'
      preLoaderRoute: typeof ApiSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stats': {
      id: '/api/stats'
      path: '/api/stats'
      fullPath: '/api/stats'
      preLoaderRoute: typeof ApiStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/clients': {
      id: '/api/clients'
      path: '/api/clients'
      fullPath: '/api/clients'
      preLoaderRoute: typeof ApiClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/clients/$id': {
      id: '/api/clients/$id'
      path: '/$id'
      fullPath: '/api/clients/$id'
      preLoaderRoute: typeof ApiClientsIdRouteImport
      parentRoute: typeof ApiClientsRoute
    }
  }
}

interface ApiClientsRouteChildren {
  ApiClientsIdRoute: typeof ApiClientsIdRoute
}

const ApiClientsRouteChildren: ApiClientsRouteChildren = {
  ApiClientsIdRoute: ApiClientsIdRoute,
}

const ApiClientsRouteWithChildren = ApiClientsRoute._addFileChildren(
  ApiClientsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApiClientsRoute: ApiClientsRouteWithChildren,
  ApiStatsRoute: ApiStatsRoute,
  ApiSubmissionsRoute: ApiSubmissionsRoute,
  AuthReturnRoute: AuthReturnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
